##################################################################################
#
#   Conformance Pack:
#     Operational Best Practices for StorageServices
#
#   This conformance pack helps verify compliance with StorageServices requirements.
#
##################################################################################

Parameters:
  BackupPlanMinFrequencyAndMinRetentionCheckParamRequiredFrequencyUnit:
    Default: days
    Type: String
  BackupPlanMinFrequencyAndMinRetentionCheckParamRequiredFrequencyValue:
    Default: '1'
    Type: String
  BackupPlanMinFrequencyAndMinRetentionCheckParamRequiredRetentionDays:
    Default: '35'
    Type: String
  BackupRecoveryPointMinimumRetentionCheckParamRequiredRetentionDays:
    Default: '35'
    Type: String
Resources:
  BackupPlanMinFrequencyAndMinRetentionCheck:
    Properties:
      ConfigRuleName: backup-plan-min-frequency-and-min-retention-check
      InputParameters:
        requiredFrequencyUnit:
          Fn::If:
          - backupPlanMinFrequencyAndMinRetentionCheckParamRequiredFrequencyUnit
          - Ref: BackupPlanMinFrequencyAndMinRetentionCheckParamRequiredFrequencyUnit
          - Ref: AWS::NoValue
        requiredFrequencyValue:
          Fn::If:
          - backupPlanMinFrequencyAndMinRetentionCheckParamRequiredFrequencyValue
          - Ref: BackupPlanMinFrequencyAndMinRetentionCheckParamRequiredFrequencyValue
          - Ref: AWS::NoValue
        requiredRetentionDays:
          Fn::If:
          - backupPlanMinFrequencyAndMinRetentionCheckParamRequiredRetentionDays
          - Ref: BackupPlanMinFrequencyAndMinRetentionCheckParamRequiredRetentionDays
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::Backup::BackupPlan
      Source:
        Owner: AWS
        SourceIdentifier: BACKUP_PLAN_MIN_FREQUENCY_AND_MIN_RETENTION_CHECK
    Type: AWS::Config::ConfigRule
  BackupRecoveryPointEncrypted:
    Properties:
      ConfigRuleName: backup-recovery-point-encrypted
      Scope:
        ComplianceResourceTypes:
        - AWS::Backup::RecoveryPoint
      Source:
        Owner: AWS
        SourceIdentifier: BACKUP_RECOVERY_POINT_ENCRYPTED
    Type: AWS::Config::ConfigRule
  BackupRecoveryPointManualDeletionDisabled:
    Properties:
      ConfigRuleName: backup-recovery-point-manual-deletion-disabled
      Scope:
        ComplianceResourceTypes:
        - AWS::Backup::BackupVault
      Source:
        Owner: AWS
        SourceIdentifier: BACKUP_RECOVERY_POINT_MANUAL_DELETION_DISABLED
    Type: AWS::Config::ConfigRule
  BackupRecoveryPointMinimumRetentionCheck:
    Properties:
      ConfigRuleName: backup-recovery-point-minimum-retention-check
      InputParameters:
        requiredRetentionDays:
          Fn::If:
          - backupRecoveryPointMinimumRetentionCheckParamRequiredRetentionDays
          - Ref: BackupRecoveryPointMinimumRetentionCheckParamRequiredRetentionDays
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::Backup::RecoveryPoint
      Source:
        Owner: AWS
        SourceIdentifier: BACKUP_RECOVERY_POINT_MINIMUM_RETENTION_CHECK
    Type: AWS::Config::ConfigRule
  CloudtrailS3DataeventsEnabled:
    Properties:
      ConfigRuleName: cloudtrail-s3-dataevents-enabled
      Source:
        Owner: AWS
        SourceIdentifier: CLOUDTRAIL_S3_DATAEVENTS_ENABLED
    Type: AWS::Config::ConfigRule
  EbsOptimizedInstance:
    Properties:
      ConfigRuleName: ebs-optimized-instance
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EBS_OPTIMIZED_INSTANCE
    Type: AWS::Config::ConfigRule
  EbsResourcesProtectedByBackupPlan:
    Properties:
      ConfigRuleName: ebs-resources-protected-by-backup-plan
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Volume
      Source:
        Owner: AWS
        SourceIdentifier: EBS_RESOURCES_PROTECTED_BY_BACKUP_PLAN
    Type: AWS::Config::ConfigRule
  EbsSnapshotPublicRestorableCheck:
    Properties:
      ConfigRuleName: ebs-snapshot-public-restorable-check
      Source:
        Owner: AWS
        SourceIdentifier: EBS_SNAPSHOT_PUBLIC_RESTORABLE_CHECK
    Type: AWS::Config::ConfigRule
  Ec2EbsEncryptionByDefault:
    Properties:
      ConfigRuleName: ec2-ebs-encryption-by-default
      Source:
        Owner: AWS
        SourceIdentifier: EC2_EBS_ENCRYPTION_BY_DEFAULT
    Type: AWS::Config::ConfigRule
  EfsEncryptedCheck:
    Properties:
      ConfigRuleName: efs-encrypted-check
      Source:
        Owner: AWS
        SourceIdentifier: EFS_ENCRYPTED_CHECK
    Type: AWS::Config::ConfigRule
  EfsResourcesProtectedByBackupPlan:
    Properties:
      ConfigRuleName: efs-resources-protected-by-backup-plan
      Scope:
        ComplianceResourceTypes:
        - AWS::EFS::FileSystem
      Source:
        Owner: AWS
        SourceIdentifier: EFS_RESOURCES_PROTECTED_BY_BACKUP_PLAN
    Type: AWS::Config::ConfigRule
  FsxResourcesProtectedByBackupPlan:
    Properties:
      ConfigRuleName: fsx-resources-protected-by-backup-plan
      Scope:
        ComplianceResourceTypes: []
      Source:
        Owner: AWS
        SourceIdentifier: FSX_RESOURCES_PROTECTED_BY_BACKUP_PLAN
    Type: AWS::Config::ConfigRule
  S3AccountLevelPublicAccessBlocksPeriodic:
    Properties:
      ConfigRuleName: s3-account-level-public-access-blocks-periodic
      Source:
        Owner: AWS
        SourceIdentifier: S3_ACCOUNT_LEVEL_PUBLIC_ACCESS_BLOCKS_PERIODIC
    Type: AWS::Config::ConfigRule
  S3BucketAclProhibited:
    Properties:
      ConfigRuleName: s3-bucket-acl-prohibited
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_ACL_PROHIBITED
    Type: AWS::Config::ConfigRule
  S3BucketDefaultLockEnabled:
    Properties:
      ConfigRuleName: s3-bucket-default-lock-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_DEFAULT_LOCK_ENABLED
    Type: AWS::Config::ConfigRule
  S3BucketLevelPublicAccessProhibited:
    Properties:
      ConfigRuleName: s3-bucket-level-public-access-prohibited
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED
    Type: AWS::Config::ConfigRule
  S3BucketLoggingEnabled:
    Properties:
      ConfigRuleName: s3-bucket-logging-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_LOGGING_ENABLED
    Type: AWS::Config::ConfigRule
  S3BucketPolicyGranteeCheck:
    Properties:
      ConfigRuleName: s3-bucket-policy-grantee-check
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_POLICY_GRANTEE_CHECK
    Type: AWS::Config::ConfigRule
  S3BucketPublicReadProhibited:
    Properties:
      ConfigRuleName: s3-bucket-public-read-prohibited
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_READ_PROHIBITED
    Type: AWS::Config::ConfigRule
  S3BucketPublicWriteProhibited:
    Properties:
      ConfigRuleName: s3-bucket-public-write-prohibited
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_WRITE_PROHIBITED
    Type: AWS::Config::ConfigRule
  S3BucketReplicationEnabled:
    Properties:
      ConfigRuleName: s3-bucket-replication-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_REPLICATION_ENABLED
    Type: AWS::Config::ConfigRule
  S3BucketServerSideEncryptionEnabled:
    Properties:
      ConfigRuleName: s3-bucket-server-side-encryption-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
    Type: AWS::Config::ConfigRule
  S3BucketSslRequestsOnly:
    Properties:
      ConfigRuleName: s3-bucket-ssl-requests-only
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_SSL_REQUESTS_ONLY
    Type: AWS::Config::ConfigRule
  S3BucketVersioningEnabled:
    Properties:
      ConfigRuleName: s3-bucket-versioning-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_VERSIONING_ENABLED
    Type: AWS::Config::ConfigRule
  S3DefaultEncryptionKms:
    Properties:
      ConfigRuleName: s3-default-encryption-kms
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_DEFAULT_ENCRYPTION_KMS
    Type: AWS::Config::ConfigRule
  S3EventNotificationsEnabled:
    Properties:
      ConfigRuleName: s3-event-notifications-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_EVENT_NOTIFICATIONS_ENABLED
    Type: AWS::Config::ConfigRule
  S3LifecyclePolicyCheck:
    Properties:
      ConfigRuleName: s3-lifecycle-policy-check
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_LIFECYCLE_POLICY_CHECK
    Type: AWS::Config::ConfigRule
  S3ResourcesProtectedByBackupPlan:
    Properties:
      ConfigRuleName: s3-resources-protected-by-backup-plan
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_RESOURCES_PROTECTED_BY_BACKUP_PLAN
    Type: AWS::Config::ConfigRule
Conditions:
  backupPlanMinFrequencyAndMinRetentionCheckParamRequiredFrequencyUnit:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: BackupPlanMinFrequencyAndMinRetentionCheckParamRequiredFrequencyUnit
  backupPlanMinFrequencyAndMinRetentionCheckParamRequiredFrequencyValue:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: BackupPlanMinFrequencyAndMinRetentionCheckParamRequiredFrequencyValue
  backupPlanMinFrequencyAndMinRetentionCheckParamRequiredRetentionDays:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: BackupPlanMinFrequencyAndMinRetentionCheckParamRequiredRetentionDays
  backupRecoveryPointMinimumRetentionCheckParamRequiredRetentionDays:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: BackupRecoveryPointMinimumRetentionCheckParamRequiredRetentionDays
