##################################################################################
#
#   Conformance Pack:
#     Operational Best Practices for AI and ML
#
#   This conformance pack helps verify compliance with AI and ML requirements.
#
##################################################################################

Parameters:
  EcsNoEnvironmentSecretsParamSecretKeys:
    Default: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, ECS_ENGINE_AUTH_DATA
    Type: String
  EcsTaskDefinitionUserForHostModeCheckParamSkipInactiveTaskDefinitions:
    Default: 'true'
    Type: String
  EksClusterOldestSupportedVersionParamOldestVersionSupported:
    Default: '1.2'
    Type: String
  EksClusterSupportedVersionParamOldestVersionSupported:
    Default: '1.2'
    Type: String
Resources:
  CloudtrailS3DataeventsEnabled:
    Properties:
      ConfigRuleName: cloudtrail-s3-dataevents-enabled
      Source:
        Owner: AWS
        SourceIdentifier: CLOUDTRAIL_S3_DATAEVENTS_ENABLED
    Type: AWS::Config::ConfigRule
  EcsContainerInsightsEnabled:
    Properties:
      ConfigRuleName: ecs-container-insights-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::ECS::Cluster
      Source:
        Owner: AWS
        SourceIdentifier: ECS_CONTAINER_INSIGHTS_ENABLED
    Type: AWS::Config::ConfigRule
  EcsContainersNonprivileged:
    Properties:
      ConfigRuleName: ecs-containers-nonprivileged
      Scope:
        ComplianceResourceTypes:
        - AWS::ECS::TaskDefinition
      Source:
        Owner: AWS
        SourceIdentifier: ECS_CONTAINERS_NONPRIVILEGED
    Type: AWS::Config::ConfigRule
  EcsContainersReadonlyAccess:
    Properties:
      ConfigRuleName: ecs-containers-readonly-access
      Scope:
        ComplianceResourceTypes:
        - AWS::ECS::TaskDefinition
      Source:
        Owner: AWS
        SourceIdentifier: ECS_CONTAINERS_READONLY_ACCESS
    Type: AWS::Config::ConfigRule
  EcsFargateLatestPlatformVersion:
    Properties:
      ConfigRuleName: ecs-fargate-latest-platform-version
      Scope:
        ComplianceResourceTypes:
        - AWS::ECS::Service
      Source:
        Owner: AWS
        SourceIdentifier: ECS_FARGATE_LATEST_PLATFORM_VERSION
    Type: AWS::Config::ConfigRule
  EcsNoEnvironmentSecrets:
    Properties:
      ConfigRuleName: ecs-no-environment-secrets
      InputParameters:
        secretKeys:
          Fn::If:
          - ecsNoEnvironmentSecretsParamSecretKeys
          - Ref: EcsNoEnvironmentSecretsParamSecretKeys
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::ECS::TaskDefinition
      Source:
        Owner: AWS
        SourceIdentifier: ECS_NO_ENVIRONMENT_SECRETS
    Type: AWS::Config::ConfigRule
  EcsTaskDefinitionMemoryHardLimit:
    Properties:
      ConfigRuleName: ecs-task-definition-memory-hard-limit
      Scope:
        ComplianceResourceTypes:
        - AWS::ECS::TaskDefinition
      Source:
        Owner: AWS
        SourceIdentifier: ECS_TASK_DEFINITION_MEMORY_HARD_LIMIT
    Type: AWS::Config::ConfigRule
  EcsTaskDefinitionNonrootUser:
    Properties:
      ConfigRuleName: ecs-task-definition-nonroot-user
      Scope:
        ComplianceResourceTypes:
        - AWS::ECS::TaskDefinition
      Source:
        Owner: AWS
        SourceIdentifier: ECS_TASK_DEFINITION_NONROOT_USER
    Type: AWS::Config::ConfigRule
  EcsTaskDefinitionPidModeCheck:
    Properties:
      ConfigRuleName: ecs-task-definition-pid-mode-check
      Scope:
        ComplianceResourceTypes:
        - AWS::ECS::TaskDefinition
      Source:
        Owner: AWS
        SourceIdentifier: ECS_TASK_DEFINITION_PID_MODE_CHECK
    Type: AWS::Config::ConfigRule
  EcsTaskDefinitionUserForHostModeCheck:
    Properties:
      ConfigRuleName: ecs-task-definition-user-for-host-mode-check
      InputParameters:
        SkipInactiveTaskDefinitions:
          Fn::If:
          - ecsTaskDefinitionUserForHostModeCheckParamSkipInactiveTaskDefinitions
          - Ref: EcsTaskDefinitionUserForHostModeCheckParamSkipInactiveTaskDefinitions
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::ECS::TaskDefinition
      Source:
        Owner: AWS
        SourceIdentifier: ECS_TASK_DEFINITION_USER_FOR_HOST_MODE_CHECK
    Type: AWS::Config::ConfigRule
  EfsAccessPointEnforceRootDirectory:
    Properties:
      ConfigRuleName: efs-access-point-enforce-root-directory
      Scope:
        ComplianceResourceTypes:
        - AWS::EFS::AccessPoint
      Source:
        Owner: AWS
        SourceIdentifier: EFS_ACCESS_POINT_ENFORCE_ROOT_DIRECTORY
    Type: AWS::Config::ConfigRule
  EfsAccessPointEnforceUserIdentity:
    Properties:
      ConfigRuleName: efs-access-point-enforce-user-identity
      Scope:
        ComplianceResourceTypes:
        - AWS::EFS::AccessPoint
      Source:
        Owner: AWS
        SourceIdentifier: EFS_ACCESS_POINT_ENFORCE_USER_IDENTITY
    Type: AWS::Config::ConfigRule
  EfsEncryptedCheck:
    Properties:
      ConfigRuleName: efs-encrypted-check
      Source:
        Owner: AWS
        SourceIdentifier: EFS_ENCRYPTED_CHECK
    Type: AWS::Config::ConfigRule
  EfsInBackupPlan:
    Properties:
      ConfigRuleName: efs-in-backup-plan
      Source:
        Owner: AWS
        SourceIdentifier: EFS_IN_BACKUP_PLAN
    Type: AWS::Config::ConfigRule
  EksClusterOldestSupportedVersion:
    Properties:
      ConfigRuleName: eks-cluster-oldest-supported-version
      InputParameters:
        oldestVersionSupported:
          Fn::If:
          - eksClusterOldestSupportedVersionParamOldestVersionSupported
          - Ref: EksClusterOldestSupportedVersionParamOldestVersionSupported
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::EKS::Cluster
      Source:
        Owner: AWS
        SourceIdentifier: EKS_CLUSTER_OLDEST_SUPPORTED_VERSION
    Type: AWS::Config::ConfigRule
  EksClusterSupportedVersion:
    Properties:
      ConfigRuleName: eks-cluster-supported-version
      InputParameters:
        oldestVersionSupported:
          Fn::If:
          - eksClusterSupportedVersionParamOldestVersionSupported
          - Ref: EksClusterSupportedVersionParamOldestVersionSupported
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::EKS::Cluster
      Source:
        Owner: AWS
        SourceIdentifier: EKS_CLUSTER_SUPPORTED_VERSION
    Type: AWS::Config::ConfigRule
  EksEndpointNoPublicAccess:
    Properties:
      ConfigRuleName: eks-endpoint-no-public-access
      Source:
        Owner: AWS
        SourceIdentifier: EKS_ENDPOINT_NO_PUBLIC_ACCESS
    Type: AWS::Config::ConfigRule
  EksSecretsEncrypted:
    Properties:
      ConfigRuleName: eks-secrets-encrypted
      Source:
        Owner: AWS
        SourceIdentifier: EKS_SECRETS_ENCRYPTED
    Type: AWS::Config::ConfigRule
  EmrKerberosEnabled:
    Properties:
      ConfigRuleName: emr-kerberos-enabled
      Source:
        Owner: AWS
        SourceIdentifier: EMR_KERBEROS_ENABLED
    Type: AWS::Config::ConfigRule
  EmrMasterNoPublicIp:
    Properties:
      ConfigRuleName: emr-master-no-public-ip
      Scope:
        ComplianceResourceTypes: []
      Source:
        Owner: AWS
        SourceIdentifier: EMR_MASTER_NO_PUBLIC_IP
    Type: AWS::Config::ConfigRule
  S3AccountLevelPublicAccessBlocksPeriodic:
    Properties:
      ConfigRuleName: s3-account-level-public-access-blocks-periodic
      Source:
        Owner: AWS
        SourceIdentifier: S3_ACCOUNT_LEVEL_PUBLIC_ACCESS_BLOCKS_PERIODIC
    Type: AWS::Config::ConfigRule
  S3BucketAclProhibited:
    Properties:
      ConfigRuleName: s3-bucket-acl-prohibited
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_ACL_PROHIBITED
    Type: AWS::Config::ConfigRule
  S3BucketDefaultLockEnabled:
    Properties:
      ConfigRuleName: s3-bucket-default-lock-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_DEFAULT_LOCK_ENABLED
    Type: AWS::Config::ConfigRule
  S3BucketLevelPublicAccessProhibited:
    Properties:
      ConfigRuleName: s3-bucket-level-public-access-prohibited
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_LEVEL_PUBLIC_ACCESS_PROHIBITED
    Type: AWS::Config::ConfigRule
  S3BucketLoggingEnabled:
    Properties:
      ConfigRuleName: s3-bucket-logging-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_LOGGING_ENABLED
    Type: AWS::Config::ConfigRule
  S3BucketPolicyGranteeCheck:
    Properties:
      ConfigRuleName: s3-bucket-policy-grantee-check
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_POLICY_GRANTEE_CHECK
    Type: AWS::Config::ConfigRule
  S3BucketPublicReadProhibited:
    Properties:
      ConfigRuleName: s3-bucket-public-read-prohibited
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_READ_PROHIBITED
    Type: AWS::Config::ConfigRule
  S3BucketPublicWriteProhibited:
    Properties:
      ConfigRuleName: s3-bucket-public-write-prohibited
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_PUBLIC_WRITE_PROHIBITED
    Type: AWS::Config::ConfigRule
  S3BucketReplicationEnabled:
    Properties:
      ConfigRuleName: s3-bucket-replication-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_REPLICATION_ENABLED
    Type: AWS::Config::ConfigRule
  S3BucketServerSideEncryptionEnabled:
    Properties:
      ConfigRuleName: s3-bucket-server-side-encryption-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_SERVER_SIDE_ENCRYPTION_ENABLED
    Type: AWS::Config::ConfigRule
  S3BucketSslRequestsOnly:
    Properties:
      ConfigRuleName: s3-bucket-ssl-requests-only
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_SSL_REQUESTS_ONLY
    Type: AWS::Config::ConfigRule
  S3BucketVersioningEnabled:
    Properties:
      ConfigRuleName: s3-bucket-versioning-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_BUCKET_VERSIONING_ENABLED
    Type: AWS::Config::ConfigRule
  S3DefaultEncryptionKms:
    Properties:
      ConfigRuleName: s3-default-encryption-kms
      Scope:
        ComplianceResourceTypes:
        - AWS::S3::Bucket
      Source:
        Owner: AWS
        SourceIdentifier: S3_DEFAULT_ENCRYPTION_KMS
    Type: AWS::Config::ConfigRule
  SagemakerEndpointConfigurationKmsKeyConfigured:
    Properties:
      ConfigRuleName: sagemaker-endpoint-configuration-kms-key-configured
      Source:
        Owner: AWS
        SourceIdentifier: SAGEMAKER_ENDPOINT_CONFIGURATION_KMS_KEY_CONFIGURED
    Type: AWS::Config::ConfigRule
  SagemakerNotebookInstanceKmsKeyConfigured:
    Properties:
      ConfigRuleName: sagemaker-notebook-instance-kms-key-configured
      Source:
        Owner: AWS
        SourceIdentifier: SAGEMAKER_NOTEBOOK_INSTANCE_KMS_KEY_CONFIGURED
    Type: AWS::Config::ConfigRule
  SagemakerNotebookNoDirectInternetAccess:
    Properties:
      ConfigRuleName: sagemaker-notebook-no-direct-internet-access
      Source:
        Owner: AWS
        SourceIdentifier: SAGEMAKER_NOTEBOOK_NO_DIRECT_INTERNET_ACCESS
    Type: AWS::Config::ConfigRule
Conditions:
  ecsNoEnvironmentSecretsParamSecretKeys:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: EcsNoEnvironmentSecretsParamSecretKeys
  ecsTaskDefinitionUserForHostModeCheckParamSkipInactiveTaskDefinitions:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: EcsTaskDefinitionUserForHostModeCheckParamSkipInactiveTaskDefinitions
  eksClusterOldestSupportedVersionParamOldestVersionSupported:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: EksClusterOldestSupportedVersionParamOldestVersionSupported
  eksClusterSupportedVersionParamOldestVersionSupported:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: EksClusterSupportedVersionParamOldestVersionSupported
