##################################################################################
#
#   Conformance Pack:
#     Operational Best Practices for EC2
#
#   This conformance pack helps verify compliance with EC2 requirements.
#
#   See Parameters section for names and descriptions of required parameters.
#
##################################################################################

Parameters:
  CloudwatchAlarmResourceCheckParamMetricName:
    Default: CPUUtilization
    Type: String
  CloudwatchAlarmResourceCheckParamResourceType:
    Default: AWS::EC2::Instance
    Type: String
  Ec2VolumeInuseCheckParamDeleteOnTermination:
    Default: 'true'
    Type: String
  ServiceVpcEndpointEnabledParamServiceName:
    Default: ec2
    Type: String
Resources:
  CloudwatchAlarmResourceCheck:
    Properties:
      ConfigRuleName: cloudwatch-alarm-resource-check
      InputParameters:
        metricName:
          Fn::If:
          - cloudwatchAlarmResourceCheckParamMetricName
          - Ref: CloudwatchAlarmResourceCheckParamMetricName
          - Ref: AWS::NoValue
        resourceType:
          Fn::If:
          - cloudwatchAlarmResourceCheckParamResourceType
          - Ref: CloudwatchAlarmResourceCheckParamResourceType
          - Ref: AWS::NoValue
      Source:
        Owner: AWS
        SourceIdentifier: CLOUDWATCH_ALARM_RESOURCE_CHECK
    Type: AWS::Config::ConfigRule
  EbsOptimizedInstance:
    Properties:
      ConfigRuleName: ebs-optimized-instance
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EBS_OPTIMIZED_INSTANCE
    Type: AWS::Config::ConfigRule
  EbsSnapshotPublicRestorableCheck:
    Properties:
      ConfigRuleName: ebs-snapshot-public-restorable-check
      Source:
        Owner: AWS
        SourceIdentifier: EBS_SNAPSHOT_PUBLIC_RESTORABLE_CHECK
    Type: AWS::Config::ConfigRule
  EncryptedVolumes:
    Properties:
      ConfigRuleName: encrypted-volumes
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Volume
      Source:
        Owner: AWS
        SourceIdentifier: ENCRYPTED_VOLUMES
    Type: AWS::Config::ConfigRule
  EbsResourcesProtectedByBackupPlan:
    Properties:
      ConfigRuleName: ebs-resources-protected-by-backup-plan
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Volume
      Source:
        Owner: AWS
        SourceIdentifier: EBS_RESOURCES_PROTECTED_BY_BACKUP_PLAN
    Type: AWS::Config::ConfigRule
  Ec2EbsEncryptionByDefault:
    Properties:
      ConfigRuleName: ec2-ebs-encryption-by-default
      Source:
        Owner: AWS
        SourceIdentifier: EC2_EBS_ENCRYPTION_BY_DEFAULT
    Type: AWS::Config::ConfigRule
  Ec2Imdsv2Check:
    Properties:
      ConfigRuleName: ec2-imdsv2-check
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_IMDSV2_CHECK
    Type: AWS::Config::ConfigRule
  Ec2InstanceDetailedMonitoringEnabled:
    Properties:
      ConfigRuleName: ec2-instance-detailed-monitoring-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_INSTANCE_DETAILED_MONITORING_ENABLED
    Type: AWS::Config::ConfigRule
  Ec2InstanceManagedBySsm:
    Properties:
      ConfigRuleName: ec2-instance-managed-by-systems-manager
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Instance
        - AWS::SSM::ManagedInstanceInventory
      Source:
        Owner: AWS
        SourceIdentifier: EC2_INSTANCE_MANAGED_BY_SSM
    Type: AWS::Config::ConfigRule
  Ec2InstanceMultipleEniCheck:
    Properties:
      ConfigRuleName: ec2-instance-multiple-eni-check
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_INSTANCE_MULTIPLE_ENI_CHECK
    Type: AWS::Config::ConfigRule
  Ec2InstanceNoPublicIp:
    Properties:
      ConfigRuleName: ec2-instance-no-public-ip
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_INSTANCE_NO_PUBLIC_IP
    Type: AWS::Config::ConfigRule
  Ec2InstanceProfileAttached:
    Properties:
      ConfigRuleName: ec2-instance-profile-attached
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_INSTANCE_PROFILE_ATTACHED
    Type: AWS::Config::ConfigRule
  Ec2ManagedinstanceAssociationComplianceStatusCheck:
    Properties:
      ConfigRuleName: ec2-managedinstance-association-compliance-status-check
      Scope:
        ComplianceResourceTypes:
        - AWS::SSM::AssociationCompliance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_MANAGEDINSTANCE_ASSOCIATION_COMPLIANCE_STATUS_CHECK
    Type: AWS::Config::ConfigRule
  Ec2ManagedinstancePatchComplianceStatusCheck:
    Properties:
      ConfigRuleName: ec2-managedinstance-patch-compliance-status-check
      Scope:
        ComplianceResourceTypes:
        - AWS::SSM::PatchCompliance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_MANAGEDINSTANCE_PATCH_COMPLIANCE_STATUS_CHECK
    Type: AWS::Config::ConfigRule
  Ec2NoAmazonKeyPair:
    Properties:
      ConfigRuleName: ec2-no-amazon-key-pair
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_NO_AMAZON_KEY_PAIR
    Type: AWS::Config::ConfigRule
  Ec2ResourcesProtectedByBackupPlan:
    Properties:
      ConfigRuleName: ec2-resources-protected-by-backup-plan
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_RESOURCES_PROTECTED_BY_BACKUP_PLAN
    Type: AWS::Config::ConfigRule
  Ec2StoppedInstance:
    Properties:
      ConfigRuleName: ec2-stopped-instance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_STOPPED_INSTANCE
    Type: AWS::Config::ConfigRule
  Ec2TokenHopLimitCheck:
    Properties:
      ConfigRuleName: ec2-token-hop-limit-check
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_TOKEN_HOP_LIMIT_CHECK
    Type: AWS::Config::ConfigRule
  Ec2VolumeInuseCheck:
    Properties:
      ConfigRuleName: ec2-volume-inuse-check
      InputParameters:
        deleteOnTermination:
          Fn::If:
          - ec2VolumeInuseCheckParamDeleteOnTermination
          - Ref: Ec2VolumeInuseCheckParamDeleteOnTermination
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::Volume
      Source:
        Owner: AWS
        SourceIdentifier: EC2_VOLUME_INUSE_CHECK
    Type: AWS::Config::ConfigRule
  EipAttached:
    Properties:
      ConfigRuleName: eip-attached
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::EIP
      Source:
        Owner: AWS
        SourceIdentifier: EIP_ATTACHED
    Type: AWS::Config::ConfigRule
  IncomingSshDisabled:
    Properties:
      ConfigRuleName: restricted-ssh
      Scope:
        ComplianceResourceTypes:
        - AWS::EC2::SecurityGroup
      Source:
        Owner: AWS
        SourceIdentifier: INCOMING_SSH_DISABLED
    Type: AWS::Config::ConfigRule
  ServiceVpcEndpointEnabled:
    Properties:
      ConfigRuleName: service-vpc-endpoint-enabled
      InputParameters:
        serviceName:
          Fn::If:
          - serviceVpcEndpointEnabledParamServiceName
          - Ref: ServiceVpcEndpointEnabledParamServiceName
          - Ref: AWS::NoValue
      Source:
        Owner: AWS
        SourceIdentifier: SERVICE_VPC_ENDPOINT_ENABLED
    Type: AWS::Config::ConfigRule
Conditions:
  cloudwatchAlarmResourceCheckParamMetricName:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: CloudwatchAlarmResourceCheckParamMetricName
  cloudwatchAlarmResourceCheckParamResourceType:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: CloudwatchAlarmResourceCheckParamResourceType
  ec2VolumeInuseCheckParamDeleteOnTermination:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: Ec2VolumeInuseCheckParamDeleteOnTermination
  serviceVpcEndpointEnabledParamServiceName:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: ServiceVpcEndpointEnabledParamServiceName
