##################################################################################
#
#   Conformance Pack:
#     Operational Best Practices for LoadBalancing
#
#   This conformance pack helps verify compliance with LoadBalancing requirements.
#
#   See Parameters section for names and descriptions of required parameters.
#
##################################################################################

Parameters:
  AlbDesyncModeCheckParamDesyncMode:
    Default: defensive, strictest
    Type: String
  ClbDesyncModeCheckParamDesyncMode:
    Default: defensive, strictest
    Type: String
  ElbCustomSecurityPolicySslCheckParamSslProtocolsAndCiphers:
    Default: Protocol-TLSv1.2
    Type: String
  ElbPredefinedSecurityPolicySslCheckParamPredefinedPolicyName:
    Default: ELBSecurityPolicy-TLS-1-2-2017-01
    Type: String
Resources:
  AlbDesyncModeCheck:
    Properties:
      ConfigRuleName: alb-desync-mode-check
      InputParameters:
        desyncMode:
          Fn::If:
          - albDesyncModeCheckParamDesyncMode
          - Ref: AlbDesyncModeCheckParamDesyncMode
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::ElasticLoadBalancingV2::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: ALB_DESYNC_MODE_CHECK
    Type: AWS::Config::ConfigRule
  AlbHttpDropInvalidHeaderEnabled:
    Properties:
      ConfigRuleName: alb-http-drop-invalid-header-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::ElasticLoadBalancingV2::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: ALB_HTTP_DROP_INVALID_HEADER_ENABLED
    Type: AWS::Config::ConfigRule
  AlbHttpToHttpsRedirectionCheck:
    Properties:
      ConfigRuleName: alb-http-to-https-redirection-check
      Source:
        Owner: AWS
        SourceIdentifier: ALB_HTTP_TO_HTTPS_REDIRECTION_CHECK
    Type: AWS::Config::ConfigRule
  AlbWafEnabled:
    Properties:
      ConfigRuleName: alb-waf-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::ElasticLoadBalancingV2::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: ALB_WAF_ENABLED
    Type: AWS::Config::ConfigRule
  AutoscalingGroupElbHealthcheckRequired:
    Properties:
      ConfigRuleName: autoscaling-group-elb-healthcheck-required
      Scope:
        ComplianceResourceTypes:
        - AWS::AutoScaling::AutoScalingGroup
      Source:
        Owner: AWS
        SourceIdentifier: AUTOSCALING_GROUP_ELB_HEALTHCHECK_REQUIRED
    Type: AWS::Config::ConfigRule
  ClbDesyncModeCheck:
    Properties:
      ConfigRuleName: clb-desync-mode-check
      InputParameters:
        desyncMode:
          Fn::If:
          - clbDesyncModeCheckParamDesyncMode
          - Ref: ClbDesyncModeCheckParamDesyncMode
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::ElasticLoadBalancing::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: CLB_DESYNC_MODE_CHECK
    Type: AWS::Config::ConfigRule
  ClbMultipleAz:
    Properties:
      ConfigRuleName: clb-multiple-az
      Scope:
        ComplianceResourceTypes:
        - AWS::ElasticLoadBalancing::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: CLB_MULTIPLE_AZ
    Type: AWS::Config::ConfigRule
  ElbAcmCertificateRequired:
    Properties:
      ConfigRuleName: elb-acm-certificate-required
      Scope:
        ComplianceResourceTypes:
        - AWS::ElasticLoadBalancing::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: ELB_ACM_CERTIFICATE_REQUIRED
    Type: AWS::Config::ConfigRule
  ElbCrossZoneLoadBalancingEnabled:
    Properties:
      ConfigRuleName: elb-cross-zone-load-balancing-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::ElasticLoadBalancing::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: ELB_CROSS_ZONE_LOAD_BALANCING_ENABLED
    Type: AWS::Config::ConfigRule
  ElbCustomSecurityPolicySslCheck:
    Properties:
      ConfigRuleName: elb-custom-security-policy-ssl-check
      InputParameters:
        sslProtocolsAndCiphers:
          Fn::If:
          - elbCustomSecurityPolicySslCheckParamSslProtocolsAndCiphers
          - Ref: ElbCustomSecurityPolicySslCheckParamSslProtocolsAndCiphers
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::ElasticLoadBalancing::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: ELB_CUSTOM_SECURITY_POLICY_SSL_CHECK
    Type: AWS::Config::ConfigRule
  ElbDeletionProtectionEnabled:
    Properties:
      ConfigRuleName: elb-deletion-protection-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::ElasticLoadBalancingV2::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: ELB_DELETION_PROTECTION_ENABLED
    Type: AWS::Config::ConfigRule
  ElbLoggingEnabled:
    Properties:
      ConfigRuleName: elb-logging-enabled
      Scope:
        ComplianceResourceTypes:
        - AWS::ElasticLoadBalancing::LoadBalancer
        - AWS::ElasticLoadBalancingV2::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: ELB_LOGGING_ENABLED
    Type: AWS::Config::ConfigRule
  ElbPredefinedSecurityPolicySslCheck:
    Properties:
      ConfigRuleName: elb-predefined-security-policy-ssl-check
      InputParameters:
        predefinedPolicyName:
          Fn::If:
          - elbPredefinedSecurityPolicySslCheckParamPredefinedPolicyName
          - Ref: ElbPredefinedSecurityPolicySslCheckParamPredefinedPolicyName
          - Ref: AWS::NoValue
      Scope:
        ComplianceResourceTypes:
        - AWS::ElasticLoadBalancing::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: ELB_PREDEFINED_SECURITY_POLICY_SSL_CHECK
    Type: AWS::Config::ConfigRule
  ElbTlsHttpsListenersOnly:
    Properties:
      ConfigRuleName: elb-tls-https-listeners-only
      Scope:
        ComplianceResourceTypes:
        - AWS::ElasticLoadBalancing::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: ELB_TLS_HTTPS_LISTENERS_ONLY
    Type: AWS::Config::ConfigRule
  Elbv2AcmCertificateRequired:
    Properties:
      ConfigRuleName: elbv2-acm-certificate-required
      Source:
        Owner: AWS
        SourceIdentifier: ELBV2_ACM_CERTIFICATE_REQUIRED
    Type: AWS::Config::ConfigRule
  Elbv2MultipleAz:
    Properties:
      ConfigRuleName: elbv2-multiple-az
      Scope:
        ComplianceResourceTypes:
        - AWS::ElasticLoadBalancingV2::LoadBalancer
      Source:
        Owner: AWS
        SourceIdentifier: ELBV2_MULTIPLE_AZ
    Type: AWS::Config::ConfigRule
Conditions:
  albDesyncModeCheckParamDesyncMode:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: AlbDesyncModeCheckParamDesyncMode
  clbDesyncModeCheckParamDesyncMode:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: ClbDesyncModeCheckParamDesyncMode
  elbCustomSecurityPolicySslCheckParamSslProtocolsAndCiphers:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: ElbCustomSecurityPolicySslCheckParamSslProtocolsAndCiphers
  elbPredefinedSecurityPolicySslCheckParamPredefinedPolicyName:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: ElbPredefinedSecurityPolicySslCheckParamPredefinedPolicyName
