##################################################################################
#
#   Conformance Pack:
#     Operational Best Practices for Secrets Manager
#
##################################################################################

Parameters:
  SecretsmanagerSecretPeriodicRotationParamMaxDaysSinceRotation:
    Default: '90'
    Type: String
    AllowedPattern: '^[0-9]*$'
    ConstraintDescription: Must contain only numbers.
  SecretsmanagerSecretUnusedParamUnusedForDays:
    Default: '90'
    Type: String
    AllowedPattern: '^[0-9]*$'
    ConstraintDescription: Must contain only numbers.
Resources:
  SecretsmanagerRotationEnabledCheck:
    Properties:
      ConfigRuleName: secretsmanager-rotation-enabled-check
      Scope:
        ComplianceResourceTypes:
        - AWS::SecretsManager::Secret
      Source:
        Owner: AWS
        SourceIdentifier: SECRETSMANAGER_ROTATION_ENABLED_CHECK
    Type: AWS::Config::ConfigRule
  SecretsmanagerScheduledRotationSuccessCheck:
    Properties:
      ConfigRuleName: secretsmanager-scheduled-rotation-success-check
      Scope:
        ComplianceResourceTypes:
        - AWS::SecretsManager::Secret
      Source:
        Owner: AWS
        SourceIdentifier: SECRETSMANAGER_SCHEDULED_ROTATION_SUCCESS_CHECK
    Type: AWS::Config::ConfigRule
  SecretsmanagerSecretPeriodicRotation:
    Properties:
      ConfigRuleName: secretsmanager-secret-periodic-rotation
      InputParameters:
        maxDaysSinceRotation:
          Fn::If:
          - secretsmanagerSecretPeriodicRotationParamMaxDaysSinceRotation
          - Ref: SecretsmanagerSecretPeriodicRotationParamMaxDaysSinceRotation
          - Ref: AWS::NoValue
      Source:
        Owner: AWS
        SourceIdentifier: SECRETSMANAGER_SECRET_PERIODIC_ROTATION
    Type: AWS::Config::ConfigRule
  SecretsmanagerSecretUnused:
    Properties:
      ConfigRuleName: secretsmanager-secret-unused
      InputParameters:
        unusedForDays:
          Fn::If:
          - secretsmanagerSecretUnusedParamUnusedForDays
          - Ref: SecretsmanagerSecretUnusedParamUnusedForDays
          - Ref: AWS::NoValue
      Source:
        Owner: AWS
        SourceIdentifier: SECRETSMANAGER_SECRET_UNUSED
    Type: AWS::Config::ConfigRule
  SecretsmanagerUsingCmk:
    Properties:
      ConfigRuleName: secretsmanager-using-cmk
      Scope:
        ComplianceResourceTypes:
        - AWS::SecretsManager::Secret
      Source:
        Owner: AWS
        SourceIdentifier: SECRETSMANAGER_USING_CMK
    Type: AWS::Config::ConfigRule
Conditions:
  secretsmanagerSecretPeriodicRotationParamMaxDaysSinceRotation:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: SecretsmanagerSecretPeriodicRotationParamMaxDaysSinceRotation
  secretsmanagerSecretUnusedParamUnusedForDays:
    Fn::Not:
    - Fn::Equals:
      - ''
      - Ref: SecretsmanagerSecretUnusedParamUnusedForDays
