name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Lint with flake8
      run: |
        pip install flake8
        cd python-rdklib
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run rdk
      run: |
        pip install rdk
        pip install rdklib
        cd python-rdklib
        rdk test-local --all
    - name: Test with pylint
      run: |
        pip install pylint
        pip install pylint_runner
        cd python-rdklib
        pylint_runner --rcfile ../.github/pylintrc
